version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=euanrae #optional
      - PASS=1234Pass #optional
    volumes:
      - transmission_data:/config
      - /srv/dev-disk-by-label-data/media/downloads:/downloads
      - /srv/dev-disk-by-label-data/media/downloads/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - jackett_data:/config
      - /srv/dev-disk-by-label-data/media/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
    volumes:
        - radarr_data:/config
        - /srv/dev-disk-by-label-data/media/movies:/movies
        - /srv/dev-disk-by-label-data/media/downloads:/downloads
    ports:
        - 7878:7878
    restart: unless-stopped

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    ports:
        - 32400:32400/tcp
        - 1900:1900/udp
        - 3005:3005/tcp
        - 5353:5353/udp
        - 8324:8324/tcp
        - 32410:32410/udp
        - 32412:32412/udp
        - 32413:32413/udp
        - 32414:32414/udp
        - 32469:32469/tcp
    environment:
        - TZ=Europe/London
        - ADVERTISE_IP=http://192.168.1.10:32400/
        - PLEX_CLAIM=PLEXCLAIM
    volumes:
        - plex_data:/config
        - plex_data:/transcode
        - /srv/dev-disk-by-label-data/media:/data

volumes:
    transmission_data:
    jackett_data:
    radarr_data:
    plex_data:
